---
title: "HMS 520 Final Project"
author: "Cassidy Chang, Yaz Ozten, and Sinclair Carr"
output: pdf_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
library("data.table")
library("ggplot2")
library("stats")
library("tidyverse")
library("mclust")
library("readr")
library("ggfortify")
library("readxl")
library("Rtsne")
library("factoextra")
library("cluster")
library("clue")
library("rigr")
library("gtsummary")
library("metafor") # for meta-regression
library("car") # for logit transformation
library("lme4") # for random effects model
library("sjstats") # for R square in lmer
library("stargazer") # displaying results in tables
library("hrbrthemes")
library("jtools") # to plot regression results
library("sjPlot") # to plot regression results
```




### Part Ia: Data Wrangling

```{r}

data <- setDT(read_excel("on-art_mort.xlsx"))
setnames(data, c("nid", "super", "meas_value", "meas_stdev", "iso3", "time_point", 
                 "age", "CD4_lower", "CD4_upper"), c("study_id", "gbd_superregion", 
                "p_mortality", "sd_p_mortality", "country_code", "time_since_art", 
                "age_group", "cd4_lower", "cd4_upper"))

data[, `:=` ("cd4_lower" = cd4_lower * 10, "cd4_upper" = cd4_upper * 10)]
data[, study_length := time_upper - time_lower]
data[, cd4_mid := (cd4_upper + cd4_lower)/2]
data[, sex := as.factor(ifelse(sex == 1, "male", "female"))]

# Identify missing values 

colnames(data)[colSums(is.na(data)) > 0]
sum(is.na(data$p_mortality)) # 20
sum(is.na(data$sd_p_mortality)) # 20
sum(is.na(data$site)) # 360

View(data)

```

  
### Part Ib: Summary statistics 

```{r}
# Summary tables
table1 <- tbl_summary(data[, c("sex", "age_group", "gbd_superregion", "time_since_art", "p_mortality", "cd4_mid")], label = list(sex ~ "Sex", age_group = "Age groups", gbd_superregion = "GBD Superregions", time_since_art = "Time since ART inititation in months", p_mortality = "Conditional probability of HIV mortality", cd4_mid = "Average CD4 count"))
table1

# Plots
boxplot(data$p_mortality~data$age_group) # Age and probability of mortality may be slightly correlated
boxplot(data$p_mortality~data$time_since_art) # Much of the data seems to be clustered in the range of six months since ART. Probability of mortality seems to decrease as time since ART increases (from six to 12 to 24 months)
require(ggplot2)
ggplot(data,aes(y=p_mortality,x=cd4_mid))+geom_point()+geom_smooth(method="lm") # Lower CD4 counts are associated with a higher probability of mortality

```

### Part IIa: Unsupervised learning - clustering 
```{r}
# Using numeric data, predict time_since_art with clustering (unsupervised learning)

# Select only numeric variables 
numeric_variables <- data[, c("p_mortality", "sd_p_mortality", "cd4_lower", "cd4_upper", 
                          "cd4_mid", "time_since_art", "sample_size", "study_length")]

# Preprocessing - scale values before unsupervised algorithm implementation
numeric_variables <- scale(replace(numeric_variables, is.na(numeric_variables), 0))

# Retrieve data on time period since ART 
true_clusters <- matrix(data$time_since_art)
prev_tsa <- c(6, 12, 24)
new_tsa <- 1:3
# Transform 6, 12, 24 to 1, 2, 3
true_clusters[true_clusters %in% prev_tsa] <- new_tsa[match(true_clusters, prev_tsa)]

# Cluster accuracy function to compute fair predictive accuracy of clustering
cluster_accuracy <- function(pred_clusters, ground_truth) {
  pts <- matrix(0, 3, 3)
  # +1 at each of (pred_clusters, ground_truth) in pts matrix
  for (val in 1:length(pred_clusters)){
    pts[pred_clusters[val], ground_truth[val]] <- 1 + 
      pts[pred_clusters[val], ground_truth[val]]}
  # Form bipartite graph by subtracting pts from max value in pts 
  bp_graph <- matrix(max(pts), 3, 3) - pts
  # Solve linear assignment problem using Hungarian algorithm 
  bp_sol <- solve_LSAP(bp_graph, maximum = FALSE)
  # Compute accuracy: sum values given by LSAP solution, divide by total no.
  accuracy <- (pts[1, bp_sol[1]] + pts[2, bp_sol[2]] + pts[3, bp_sol[3]]) / length(pred_clusters)
  return(accuracy)}

# Clustering
# Set up empty variables for future accuracy imputation
k_accuracies <- rep(NA, 10)
pam_accuracies <- rep(NA, 10)
agglom_accuracies <- rep(NA, 10)
model_accuracies <- rep(NA, 10)

# Set seed for reproducibility
set.seed(0)

for (i in 1:10) {
  # k-means clustering 
  k_results <- kmeans(as.matrix(numeric_variables), centers = 3, nstart = 1)
  k_clusters <- matrix(k_results$cluster)
  k_accuracies[i] <- cluster_accuracy(k_clusters, true_clusters)
  
  # k-medoids clustering (partition around medoids) 
  pam_results <- pam(as.matrix(numeric_variables), k = 3, nstart = 1)
  pam_clusters <- matrix(pam_results$clustering)
  pam_accuracies[i] <- cluster_accuracy(pam_clusters, true_clusters)
  
  # hierarchical clustering using Euclidean distance matrix
  dist_matrix <- dist(numeric_variables, method = "euclidean")
  h_results <- hclust(dist_matrix, method = "ward.D")
  sliced_results <- cutree(h_results, k = 3)
  agglom_clusters <- matrix(sliced_results)
  agglom_accuracies[i] <- cluster_accuracy(agglom_clusters, true_clusters)
  
  # model-based clustering 
  model_results <- Mclust(numeric_variables, G = 3)
  model_clusters <- model_results$classification
  model_accuracies[i] <- cluster_accuracy(model_clusters, true_clusters)}

# Calculate average predictive accuracy based on 10 accuracy values for each 
# clustering method 
k_mean_accuracy <- mean(k_accuracies)
pam_mean_accuracy <- mean(pam_accuracies)
agglom_mean_accuracy <- mean(agglom_accuracies)
model_mean_accuracy <- mean(model_accuracies)

cat("Mean k-means predictive accuracy is:", k_mean_accuracy, 
    "\nMean k-medoids predictive accuracy is:", pam_mean_accuracy, 
    "\nMean agglomerative predictive accuracy is:", agglom_mean_accuracy, 
    "\nMean model-based predictive accuracy is:", model_mean_accuracy)

```


### Part IIb: Visualization with PCA and tSNE

```{r}

# Prepare variables for PCA and tSNE
numeric_variables <- data[, c("p_mortality", "sd_p_mortality", "cd4_lower", "cd4_upper", 
                          "cd4_mid", "time_since_art", "sample_size", "study_length")]
numeric_variables <- scale(replace(numeric_variables, is.na(numeric_variables), 0))

# PCA visualization 
pca_result <- prcomp(numeric_variables)
summary(pca_result)
autoplot(pca_result, colour = data$time_since_art)

# tSNE visualization 
data_tsne <- Rtsne(numeric_variables, perplexity = 10, check_duplicates = FALSE)
plot(data_tsne$Y, col = data$time_since_art)

```

## Part IIIa: Regression Analyses

```{r}
# subset data for regression analyses

regr_data <- data
factor.list <- c("sex", "age_group", "gbd_superregion", "study_id", "time_since_art")

regr_data[, (factor.list) := lapply(.SD, as.factor), .SDcols = factor.list]

#data[, get(factor.list)] <- sapply(data[, get(factor.list)], as.factor)

regr_data[, var_p_mortality := sd_p_mortality^2]
regr_data[, logit_mortality := logit(p_mortality)]


regr_data[is.na(regr_data) | regr_data == "Inf" | regr_data == "-Inf"] <- NA
regr_data <- regr_data[complete.cases(regr_data)]

# weighted least squares logit linear regression
m1.1  <- lm(logit_mortality ~ time_since_art, data = regr_data, weights = 1/(sd_p_mortality^2))

stargazer(m1.1, title = "Results of unadjusted regression model", 
          dep.var.caption = "Logit(Probability of Mortality)", type = "text")

m1.2  <- lm(logit_mortality ~ time_since_art + sex + age_group + study_length, data = regr_data, weights = 1/(sd_p_mortality^2)) # how to treat ordinal variable

stargazer(m1.2, title = "Results of adjusted regression model", 
          dep.var.caption = "Logit(Probability of Mortality)", type = "text")




m1.3  <- lmer(logit_mortality ~ time_since_art + sex + age_group + study_length + (1 | study_id), data = regr_data, weights = 1/(sd_p_mortality^2)) # add random intercepts for study id

stargazer(m1.3, title = "Results of regression model with random intercepts", 
          dep.var.caption = "Logit(Probability of Mortality)", type = "text")

performance::r2(m1.3)


pe.m1.1 <- coef(m1.1)  # parameters
ll.m1.1 <- logLik(m1.1)  # likelihood at maximum

pe.m1.2 <- coef(m1.2)  # parameters
ll.m1.2 <- logLik(m1.2)  # likelihood at maximum
```

# Aikaike Information Criterion

$$
AIC\ (M) = D(M) + 2 \times |M|
$$

```{r}
k.m1.1 <- length(pe.m1.1)
k.m1.2 <- length(pe.m1.2)

aic.m1.1 <- 2*k.m1.1 - 2*ll.m1.1
aic.m1.2 <- 2*k.m1.2 - 2*ll.m1.2

aic.test <- aic.m1.2 - aic.m1.1 ; aic.test
``` 

# Bayesian Information Criterion

$$
BIC\ (M) = D(M) + \log(n) \times |M|
$$

```{r}
bic.m1.1 <- log(nrow(regr_data))*k.m1.1 - 2*ll.m1.1
bic.m1.2 <- log(nrow(regr_data))*k.m1.2 - 2*ll.m1.2

bic.test <- bic.m1.2 - bic.m1.1 ; bic.test
```


## Meta regression

```{r}
# meta regression models
m2.1 <- rma.mv(logit(p_mortality), var_p_mortality, data = regr_data, method = "ML", 
             mods = ~ time_since_art + sex + age_group + study_length)
summary(m1)

m2.2 <- rma.mv(logit(p_mortality), var_p_mortality, data = regr_data, method = "ML", 
             mods = ~ time_since_art + sex + age_group + study_length, random = ~ 1 | study_id)
summary(m2)

```

### Part IIIb: Visualization

```{r}
# Plot probability of dying per GBD Superregion

outcome1 <- ggplot(data = regr_data, aes(x = p_mortality, group = gbd_superregion, fill = gbd_superregion)) + geom_density(adjust = 1.5, alpha = 0.4) + theme_minimal()
outcome1 + labs(x = "Probability of HIV mortality", y = "Density") + theme(legend.position = c(0.9, 0.8), legend.direction = "vertical") + scale_fill_discrete(name = "GBD Superregion", breaks = c("high", "ssa",  "other"), labels = c("High income", "Sub-Saharan Africa", "Other")) + theme(plot.title = element_text(hjust = 0.5))

# Plot regression results

result_plot1 <- plot_summs(m1.1, m1.2, coefs = c("12 months since ART initiation" = "time_since_art12", "24 months since ART initiation" = "time_since_art24", "Females" = "sex", "25 to 35 years" = "age_group25_35", "35 to 45 years" = "age_group35_45", "45 to 55 years" = "age_group45_55", "55 to 100 years" = "age_group55_100", "Length of study" = "study_length"),
           scale = TRUE, robust = TRUE)
result_plot1

result_plot2 <- plot_models(m1.1, m1.2, axis.labels = c("12 months since ART initiation", "24 months since ART initiation", "Females", "25 to 35 years", "35 to 45 years", "45 to 55 years","55 to 100 years", "Length of study"), wrap.labels = 20)
result_plot2
#  Time since ART and probability of dying


GeomSplitViolin <- ggproto("GeomSplitViolin", GeomViolin, 
                           draw_group = function(self, regr_data, ..., draw_quantiles = NULL) {
  data <- transform(data, xminv = x - violinwidth * (x - xmin), xmaxv = x + violinwidth * (xmax - x))
  grp <- data[1, "group"]
  newdata <- plyr::arrange(transform(data, x = if (grp %% 2 == 1) xminv else xmaxv), if (grp %% 2 == 1) y else -y)
  newdata <- rbind(newdata[1, ], newdata, newdata[nrow(newdata), ], newdata[1, ])
  newdata[c(1, nrow(newdata) - 1, nrow(newdata)), "x"] <- round(newdata[1, "x"])

  if (length(draw_quantiles) > 0 & !scales::zero_range(range(data$y))) {
    stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <=
      1))
    quantiles <- ggplot2:::create_quantile_segment_frame(data, draw_quantiles)
    aesthetics <- data[rep(1, nrow(quantiles)), setdiff(names(data), c("x", "y")), drop = FALSE]
    aesthetics$alpha <- rep(1, nrow(quantiles))
    both <- cbind(quantiles, aesthetics)
    quantile_grob <- GeomPath$draw_panel(both, ...)
    ggplot2:::ggname("geom_split_violin", grid::grobTree(GeomPolygon$draw_panel(newdata, ...), quantile_grob))
  }
  else {
    ggplot2:::ggname("geom_split_violin", GeomPolygon$draw_panel(newdata, ...))
  }
})

geom_split_violin <- function(mapping = NULL, data = NULL, stat = "ydensity", position = "identity", ..., 
                              draw_quantiles = NULL, trim = TRUE, scale = "area", na.rm = FALSE, 
                              show.legend = NA, inherit.aes = TRUE) {
  layer(data = data, mapping = mapping, stat = stat, geom = GeomSplitViolin, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes, 
        params = list(trim = trim, scale = scale, draw_quantiles = draw_quantiles, na.rm = na.rm, ...))
}

plot1 <- ggplot(regr_data, aes(x=time_since_art, y = p_mortality, fill = sex)) + geom_split_violin(trim = F) + theme_minimal()

plot1 + labs(y = "Probability of HIV mortality", x = "Time since initiation of ART", fill = "Sex") + theme(legend.position = c(0.9, 0.9), legend.direction = "vertical") + scale_fill_discrete(name="Sex",breaks=c("1", "2"),labels = c("Male", "Female"))

```
